apiVersion: apps/v1
kind: Deployment
metadata:
  name: dash
  labels:
    deployment: dash
spec:
  replicas: 2
  selector:
    matchLabels:
      pod: dash
  template:
    metadata:
      labels:
        pod: dash
    spec:

      containers:
        - name: dash
          image: pablorr10/nlp:mongo_dash
          imagePullPolicy: Always
          ports:
            - containerPort: 8050
          env:

            # Kind of deployment
            - name: DEPLOYMENT
              value: minikube

            # # dash Env Variables
            # - name: SU_NAME
            #   value: pablorr10

            # - name: SU_EMAIL
            #   value: pablo.ruiz@basf.com

            # - name: SU_PASSWORD
            #   value: pppp

            # mongo Env Variables
            - name: MONGO_USER
              value: pablominikube

            - name: MONGO_PASSWORD
              value: password

            - name: MONGO_DB
              value: app-test

            - name: MONGO_HOST
              value: mongo-service

      initContainers:

        - name: init-mongo-service
          image: busybox
          command: ['sh', '-c', 'until nslookup mongo-service; do echo waiting for mongo-service; sleep 2; done;']
        
        - name: init-dash-service
          image: busybox
          command: ['sh', '-c', 'until nslookup dash-service; do echo waiting for dash-service; sleep 2; done;']
  