kind: Service
apiVersion: v1
metadata:
  name: mongo-service
spec:
  selector:
    app: mongo-container
  ports:
  - name: mongo
    protocol: TCP
    port: 5000
    targetPort: 5000
  type: ClusterIP