paths: 
    results: results/
    catalog: data/catalog
    checkpoints: checkpoints/
    stopwords: data/stopwords/
    data: data/knowledge_dashboard

topic: isocyanate
classes: [relevant, irrelevant]