paths: 
    data: data/
    images: images/
    results: results/
    catalog: data/catalog
    documents: data/documents
    checkpoints: checkpoints/
    stopwords: data/stopwords/

topic: isocyanate
classes: [relevant, irrelevant]